### ISSUE TITLE
System Wide - Merge Contact Records

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#1]
**Source:**
Repository: dhenry-KCI / FredCo-Post-Go-Live-
Issue #: 91
Entered By: Ashlye Bonomo
[Jump to this repository](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/91) 

**Request:**
Would like the ability to merge contact records to further manage the duplication of contacts and permits associated to them in IPS.

*Christian marked this item as an enhancement because the system does not currently support this out of the box.

**Comment by ABonomo21** [comment]
I think we need the functionality to Merge Contact records

**Comment by ABonomo21** [comment]
follow up with Infor would like this

**Comment by ABonomo21** [comment]
closing this ticket- staff has been cleaning up duplicate contacts manually
