### ISSUE TITLE
Building Permits - Town Permits - Sending COC & COO Reports

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#10]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2098
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2098) 

**Request:**
Ensure that the correspondence sent for COCs or COOs that are in a town are only sent to the generic town email address. It should not send to the other applicants on the application.

**Comment by ABonomo21** [comment]
We need to check with Emily to see if this has been working okay since the town reviewer fix was made on notifications. Emily sends all coo and coc's lets see where there can be improvement but i would think it would be a phase 2 or a low priority in phase 1B....

**Comment by ABonomo21** [comment]
moved
