### ISSUE TITLE
R4C Detail Page Text Field Character Length Restrictions

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#101]
We have received several error messages from customers who are typing information into text fields on detail pages that exceeds the allowed characters. This results in a large error message and the application cannot be submitted.

We need to proactive and ensure applicants cannot type any characters past the allowed limit to prevent these error messages for customers in the future. It is not always easy to get the information the applicant is trying to enter and pinpoint which field is being exceeded.

**Comment by JuanitaMiles** [comment]
Migrated to FredCo_Phase2_FY21 ticket # [10](https://github.com/JuanitaMiles/FredCo_Phase2_FY21/issues/10)

**Comment by ABonomo21** [comment]
completed
