### ISSUE TITLE
Building Permits - Grading - As-Built Submission Process Follow Up

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#11]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2091
Requested By: Ashlye Bonomo, Eric Dodson
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2091) 

**Request:**
We need to follow up on how the submission of CAD as builts will be delivered to the County and routed to Eric. Currently Mary M in GIS is receiving the documentation for GIS database purposes. So we want to see if the delivery to her will be part of the routing to the ECS team.

**Comment by ABonomo21** [comment]
DUPLICATE
