### ISSUE TITLE
SWMTRI Workflow Adjustments

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#111]
•	Application Type = Grading; Work Type = SWMTRI
o	Will not perform any bulk status/milestone changes at this time. We will take the time to review any possible workflow changes that will better notate what stage the application is in with Dan. SWMTRIs remain active indefinitely in order to perform the triennial inspections.

SWM-TRI and PI ensure that the renewal notifications aren’t sent. Ensure the expiration date is out in the future.

**Comment by ABonomo21** [comment]
completed
