### ISSUE TITLE
Land Use Placard Missing Start/End Dates

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#113]
Issue reported by Abbie White:

I’ve got a Land Use permit L260017 that we issued this morning but the placard will not show the start/end dates for the event. I’ve got the dates added in both the details page and on the job description but they still won’t show. They just say “NA”

![image](https://user-images.githubusercontent.com/47611580/86961496-501e2d00-c12f-11ea-8789-6390aa492fea.png)

![image](https://user-images.githubusercontent.com/47611580/86961507-54e2e100-c12f-11ea-9a6c-10a6acdd8d7b.png)

**Comment by TaraF** [comment]
@ABonomo21 @JuanitaMiles  - this has been updated to use the Land Use Intake Details now.  Ready for testing.

**Comment by JuanitaMiles** [comment]
@TaraF Checked same application in TEST. Looks good. Please promote change to prod.

![image](https://user-images.githubusercontent.com/31770504/89135764-caa75600-d4fd-11ea-8af2-d79247cc64ec.png)

**Comment by TaraF** [comment]
@JuanitaMiles  - this has been push to Production.

**Comment by JuanitaMiles** [comment]
Confirmed, closing.
