### ISSUE TITLE
Gaming Permit - Mostly Blank Issuance Report

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#114]
Gaming Permit G260023 - The Gaming Permit - Official Issuance report is running with only the Name of the applicant. None of the other typical language/formatting is appearing.

Can you help us understand why this might be happening? I know that the permit is missing some typical information like start/end date, but I've been able to run the report in test without these dates and the report formatting will still look good, the dates will just be missing.

![image](https://user-images.githubusercontent.com/47611580/86961596-78a62700-c12f-11ea-9261-c373ac52560d.png)

**Comment by JuanitaMiles** [comment]
Has been addressed and deployed to production. Closing.
