### ISSUE TITLE
Zoning Cert Issuance correspondence

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#115]
Zoning Certificate once issued is adding the official issuance document (which generates blank) and should be adding the Zoning Certificate document. OLD TICKET 588 in post go live list

see example 192611 in production
generating this report

![image](https://user-images.githubusercontent.com/47611580/86961658-95425f00-c12f-11ea-88ca-152156e18208.png)
blank
![image](https://user-images.githubusercontent.com/47611580/86961669-9a071300-c12f-11ea-8948-7f608de13517.png)
should add this report labeled zoning cert in the documents menu
![image](https://user-images.githubusercontent.com/47611580/86961690-a12e2100-c12f-11ea-8ba4-7e683baf3fbb.png)

![image](https://user-images.githubusercontent.com/47611580/86961702-a5f2d500-c12f-11ea-8727-a7fd7459cb09.png)

I think I might have had a revelation...
@megisys Dan can you confirm whether or not the batch job for permit extensions ALWAYS sends the Building Permit Official Issuance report no matter the permit type (aside from grading & driveway of course). Zoning Certificate should not receive the typical Building Permit Official Issuance. It has it's own issuance report: Zoning Certificate.

On Permit 192611 the extension log/review dates correspond pretty closely to when the extension/official issuance attachments were added. 6/16-6/17 I feel like this is probably why we are seeing the incorrect issuance report being generated.

The original Zoning cert didn't generate because it was issued prior to go live, outside of the new correspondence process.

**Comment by megisys** [comment]
145586 - This was very initally very unclear to me. I believe it was the res-issuance after an EXT request. If so. Please see 145586 in Test and it is now creating the right one for ZONING  Correspondence. = EXT After Fee Formula Change
