### ISSUE TITLE
Fee Estimation Detail Pages

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#116]
PLease Log into TEST and on RESBLDG (Only at this Point). PLease add the detail page to an existing Building Permit which the fees are not yet added.. OR... Start a fresh RESBLDG and see the Estimate Page. - Access Contol will need to be updated

![image](https://user-images.githubusercontent.com/47611580/86961882-f702c900-c12f-11ea-9d33-fe28f2e5be0d.png)

**Comment by ABonomo21** [comment]
Ready for retest on resbldg

**Comment by ABonomo21** [comment]
Reviewed - 288557 would like to move forward with having this available on all building and use permits. 

Lets also put this in front of Ashley R. to see if she would find it useful.

**Comment by JuanitaMiles** [comment]
Migrated to FredCo_Phase2_FY21 ticket # [6](https://github.com/JuanitaMiles/FredCo_Phase2_FY21/issues/6)

**Comment by ABonomo21** [comment]
completed
