### ISSUE TITLE
Condo Home Builder Fees

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#119]
The home builder fee did not auto generate on condo units 287772-287780
![image](https://user-images.githubusercontent.com/47611580/86964189-a8572e00-c133-11ea-835e-d7499c70079c.png)

however it did on 2877771

![image](https://user-images.githubusercontent.com/47611580/86964136-98d7e500-c133-11ea-94db-11c0b0e8898e.png)
home builder fee should be assessed on all CONDO units not the parent. and not on apartments.

**Comment by JuanitaMiles** [comment]
migrated to current repository for now. If Dan does not address before Monday, will incorporate into first sprint.
