### ISSUE TITLE
Health Review Assignment

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#120]
Review all building and use permits that have a health review to ensure the auto assignment it assigned to Kim Dillman and Not Karen Amoss

**Comment by JuanitaMiles** [comment]
Migrated to FredCo_Phase2_FY21 ticket # [11](https://github.com/JuanitaMiles/FredCo_Phase2_FY21/issues/11)

**Comment by ABonomo21** [comment]
completed
