### ISSUE TITLE
RESBLDG - Child Permit / Impact Fee Workflow Issues

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#122]
This is another thing we need to address these permits are not at the correct milestone. Pending approval from the child permits already paid impact waiting for batch stamp and the milestone is awaiting applicant payment.. ??

Need to review this process overall and determine if there are any adjustments to the workflow/milestones that can be made to make the process of issuance of child permits, impact fee payment (and subsequent July 1 updates), run more smoothly.

**Comment by JuanitaMiles** [comment]
Migrated to FredCo_Phase2_FY21 ticket # [5](https://github.com/JuanitaMiles/FredCo_Phase2_FY21/issues/5)

**Comment by ABonomo21** [comment]
completed
