### ISSUE TITLE
R4C - Building Permit Re-Submission Process Enhancements

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#123]
Per discussion with Dan. We will explore and implement the updates to:

- Applicant Actions Detail Page : Name change, Language updates, and Action field selection options

- Status Check : Language updates

- "Request Application Revision" button : turn on with log type, language updates.

- Logs Section: make available, ensure appropriate log types are visible, explore what pieces of data can be shown within.

**Comment by ABonomo21** [comment]
completed
