### ISSUE TITLE
Liquor License - Requested Updates

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#125]
Email from Tara 7/15/20:

Hi Juanita,

I met with Ashley this morning to review some report updates, and out of that discovery came a few changes / additions need for IPS itself, based on some new law changes that have come into effect.  

Below I am just listing out what we talked about at a high level, but obviously this should be a larger discussion that you will need to kickoff with the right people.  Also, if you want me to add it to Github in the new repository I certainly can, but I see you inputting things in a different way, so I wasn’t sure how /who /what happens there 😊

High Priority items:
•	New Classes needed in IPS:
o	DDS – Distillery
o	B-A – Arena Beer & Wine
o	CT – Cinema / Theater 
o	M-G – Muncipal Golf Course

•	New Category needed for IPS:
o	L-L Liquor Only

•	New Endorsements needed for IPS:
o	Salon 

Lower Priority items:
•	Need a check box for DBR class licenses, to indicate the manufactor license is after 2017 and they now want to add a tasting room (this will drive what hours they can operate, which in turn effects report)

Thanks,
Tara

**Comment by ABonomo21** [comment]
resolved with Christian
