### ISSUE TITLE
Reports for Dial - All Permits Issued

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#128]
KCI to create a new report "All Permits Issued".

Report will replicate the same setup as the old report attached.
Report will display data from go-live forward.

[12_2019.All.Permits.Issued.pdf](https://github.com/JuanitaMiles/FredCo_Future_Phases/files/5004657/12_2019.All.Permits.Issued.pdf)

_*Ticket is being broken out from #117 for better tracking._

**Comment by ABonomo21** [comment]
completed
