### ISSUE TITLE
Reports for Dial - Non Res Permit Issued

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#129]
KCI to create a new report "Non Res Permit Issued".

Report will replicate the same setup as the old report attached.
Report will display data from go-live forward.

[12_2019.Non.Res.Permit.Issued.pdf](https://github.com/JuanitaMiles/FredCo_Future_Phases/files/5004667/12_2019.Non.Res.Permit.Issued.pdf)

_*Ticket is being broken out from #117  for better tracking._

**Comment by ABonomo21** [comment]
completed
