### ISSUE TITLE
R4C - Loading Time Issues

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#13]
**Source:**
Repository: dhenry-KCI / FredCo-Post-Go-Live-
Ticket #: 168
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/168) 

**Request:**
Customers have reported very long loading times when using the Rhythm for Civics portal.

*Dan G. commented that an upgrade will be carried out on Tuesday (1/21/20) in the TEST environment, and will need testing.

**Comment by ABonomo21** [comment]
closing this ticket we have had great response from applicants on the production environment.
