### ISSUE TITLE
System Wide - GIS - IPS Address Cleanup

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#14]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2063
Requested By: Project Team
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2063) 

**Request:**
We will need to continue to monitor the clean up needed on parcels/addresses. This issue originally references duplicate addresses only, but this can be expanded to:

- Water/Sewer details
- Changes in Water/Sewer designation due to new/future development
- Subdivision updates
- Road Details (county/sha)
- Parcel/Address relationships

**Comment by ABonomo21** [comment]
This should be moved to current github to be combined with the current ticket we have.
