### ISSUE TITLE
Building Permits - Fire Permit - Fire Details Page Design and Mapping

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#16]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 1937 & 1840
Requested By: Ashlye Bonomo
[1937: Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1937) 
[1840: Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1840)

**Request:**
1937 - This ticket references the difficulties in formatting the Fire Intake Details page, specifically the headers in R4C.
1840 - This ticket references the request to have the details populated on the Fire Intake Details page automatically populate in the back office Fire Details page. This would require mapping the fields between the two pages.

**Comment by ABonomo21** [comment]
Fire permits have been working - It is not ideal to have the process so different from the other application types but i think this is definitely a phase 2 low priority
