### ISSUE TITLE
PDox - Task Acceptance Message Customization

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#17]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 1741
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1741) 

**Request:**
Ashlye wanted the ability to insert SOP type instructions on the popup asking "Do you want to accept this task?"

Robert responded with information that you can change the wording of the popup but it can only be a single wholesale change. It can not be customized per task that is being accepted.

Ashlye agreed to reassess after go live if there is an issue with staff following operating procedures in PDox.

**Comment by ABonomo21** [comment]
i would still like to have this completed. Although i think Ash Reed has some good recommendations regarding the documentations that we can add to the pdox log in page - similar to what MoCo has which would include documentation and instructions on naming conventions SOP's etc. 

With that said i am not sure this is needed. I will let Ashley and Mike make the final call on this...
