### ISSUE TITLE
Planning - "Revision Assignment" for Internal Review Re-submissions

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#18]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 1494
Requested By: Mike Wilkins; Ashley Reed
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1494) 

**Request:**
Mike and Ashley would like to implement a "Revision Assignment" solution similar to what Building Permits have. Building and Use permits currently are configured with a Revision Assignment milestone that generates after an applicant completes the Applicant Actions resubmit. During this milestone, intake staff review the information that has been resubmitted, adds any necessary reviews to the application and completes the ASSIGN condition. Once the condition is approved, the application progresses back to the Under Review milestone.

A "Review Assignments Required" dashboard item was created as solution until this configuration is completed.

**Comment by ABonomo21** [comment]
This functionality has worked great for permitting and I think Planning would benefit from it - however we only have revision assignment task for internal review... it is super convenient to have it show up on a dashboard to ensure review assignment is not missed. Dan can model what permits has to make this work for planning.

**Comment by ABonomo21** [comment]
A. Reed okay with current process
