### ISSUE TITLE
System Wide - Add Milestone Column to "Other Applications and Cases" Grid

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#2]
**Source:**
Repository: dhenry-KCI / FredCo-Post-Go-Live-
Ticket #: 90
Requested By: Ashlye Bonomo / Juanita Miles
[Jump to this repository](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/90) 

**Request:**
Can we add a column to the "Other Applications and Cases" grid on the Related Records tab that will indicate the milestone the application or case is in?

![image](https://user-images.githubusercontent.com/31770504/72376874-b70cdd00-36dc-11ea-86c2-051b7066e231.png)

*Christian noted the other application and cases field doesn't allow for milestone grid since it is on different product families.

**Comment by ABonomo21** [comment]
nice to have talk to infor about future functionality
