### ISSUE TITLE
R4C - Inspection Requests/Results During Inspection Milestones

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#20]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Managment
Ticket #: 1447
Requested By: Ashlye Bonomo / Juanita Miles
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1447) 

**Request:**
This ticket addressed the potential confusion on the request inspections grid on the Needs Action page of R4C. The grid does not show whether or not an inspection is a second cycle, it simply prompts you to request another inspection. We saw this as potentially confusing to applicants if they aren't seeing that the inspection they are requesting is a first, second, third...

**Comment by ABonomo21** [comment]
I have not heard to many concerns about this. I think it is self explanatory on the portal. lets ask bob if he has had any different feedback.
