### ISSUE TITLE
System Wide - Cross Module Dashboard Reports

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#21]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 1423
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1423) 

**Request:**
Due to the high volume of information needed on the My Infor dashboard we would like to consider creating custom dashboard reports that allows for information across modules to be displayed in a single dashboard item.

This issue is most apparent for the permits staff but we should ensure the needs for planning admin staff are met as well while gathering requirements.

See the original issue for Dan's initial markups.

**Comment by ABonomo21** [comment]
this is something we may want to look into for phase 2 but dahsboards are working and manageable for now as they are...

**Comment by ABonomo21** [comment]
no required
