### ISSUE TITLE
Building Permits - Expiration Notifications

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#22]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 1269
Requested By: Ashlye Bonomo / Juanita Miles
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1269) 

**Request:**
This ticket touched on the need for Dan to look into the expiration notifications. Dan responded with the need to wait until after go live to address this.

This has continued to be a large issue post go live, as expiration notices are still not going out automatically as of 1/16/20.

**Comment by ABonomo21** [comment]
this has been working since the upgrade as long as the batch manager runs. - closing this ticket.
