### ISSUE TITLE
System Wide - Expiring Hansen7 Milestones in IPS

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#23]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 1241
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1241) 

**Request:**
This ticket was created as a reminder to expire the old stage progression statuses/milestones from Hansen7 post go-live.

**Comment by ABonomo21** [comment]
we still need to expire these old stage progressions so they do not show up on the change status/milestone option - this is another task we should move to new github and assign to Jeff Wisner.

**Comment by ABonomo21** [comment]
moved
