### ISSUE TITLE
System Wide - Remove "[Suactkey=...]" From Review Names

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#25]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 1099
Requested By: Project Team
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1099) 

**Request:**
Need to remove the "[Suactkey=...]" from all Review Descriptions in IPS. This was identified as a go-live task. Just need general confirmation from project team these are all gone.

**Comment by ABonomo21** [comment]
This clean up was done. I am going to close this ticket.
