### ISSUE TITLE
System Wide - Log Type Clean Up

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#26]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 995
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/995) 

**Request:**
Log types in IPS need to be cleaned up. Ashlye indicated a list was provided to County IIT to complete this task.

Due to changes in County IIT staff, we will need to confirm if this task was completed, if not, who will complete. (See original issue)

**Comment by ABonomo21** [comment]
I would like to do this and think it should be a task assigned to IIT - this can be moved to the current Github for Jeff W.

**Comment by ABonomo21** [comment]
moved
