### ISSUE TITLE
R4C - Detail Page Edit Option After Completeness Check Approval

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#27]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 932
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/932) 

**Request:**
This issue went through several different evolutions...The end result was to ensure applicants could not edit application details pages (other than the applicant actions), after the Completeness Check review has been approved. This was accomplished as a temporary fix using a formula, however the 20.1 R4C release is supposed to have a feature to disable the "Edit" button.

(See original issue for full evolution of this item)

**Comment by ABonomo21** [comment]
this has been working fine- closing
