### ISSUE TITLE
Planning - PLAT/SITE - Remove "Initial" From Fee Descriptions

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#29]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 464 & 391
Requested By: Ashley Reed
[464 - Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/464) 
[391 - Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/391)

**Request:**
Remove the "Initial" wording from the fee descriptions. We will need a word to replace initial since removing initial without replacing it with something will cause duplicate fee descriptions.

![image](https://user-images.githubusercontent.com/31770504/72583195-67343e80-38b3-11ea-977f-70ce6c217a7b.png)

![image](https://user-images.githubusercontent.com/31770504/72583409-37396b00-38b4-11ea-93ec-f8ef27ca87e6.png)

**Comment by MLWilkins** [comment]
this can be closed.
