### ISSUE TITLE
System Wide - Fee Change Recalculation

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#3]
**Source:**
Repository: dhenry-KCI / FredCo-Post-Go-Live-
Ticket #: 163
Requested By: Mike Wilkins
[Jump to this repository](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/163) 

**Request:**
This issue was originally created to address the school construction fees that did not update on in-life projects upon the fee increase on 1/1/20. However it appears the issue is larger, as Infor will need to complete the fee recalculation configuration for when fee schedules are updated July 1 of each year, for the system as a whole.

Please see source issue above for more information.

**Comment by ABonomo21** [comment]
related to a current github ticket which needs to be address- along with the budget string ticket Jeff Wisner should be able to do this and will need time with Dan to train

**Comment by ABonomo21** [comment]
moved
