### ISSUE TITLE
Building Permits - Minor Grading - Pending Certificate Milestone

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#30]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 196
Requested By: Tiffany Martin
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/196) 

**Request:**
This issue was originally created to ensure the CERTREV review does not populate along with the pending certificate milestone for minor grading. The expectation was that the application should skip the pending certificate milestone and generate an email alerting the applicant the permit has been closed. Correspondence was cited as an issue for making this change.

Grading permits have undergone several changes since this issue was created. Need to confirm the minor grading configuration, report/correspondence is working as expected for the closure of the permit.

**Comment by ABonomo21** [comment]
Lets check in with Emily to see how this has been working. If it still needs work we should move to the current github and address while we have support.
