### ISSUE TITLE
System Wide - Expiring Old Inspectors or Employee Records

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#32]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2180
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2180) 

**Request:**
Ticket originally addressed the need to expire old inspectors that are showing as available to assign and result inspections in IPS. (WSummer, JWilhelm).

This can be expanded to included any staff that does not work at the County any longer.

**Comment by ABonomo21** [comment]
This should be moved to current github and assigned to Jeff Wisner, like to the log clean up. We should expire all old employee records..

**Comment by ABonomo21** [comment]
moved to current github
