### ISSUE TITLE
Building Permits - Rules for Inspection Requests and Status of Child Permits

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#33]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2203
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2203) 

**Request:**
Initial efforts were to made to identify what the status of a Child permit/inspection must be before a parent inspection can be requested. Need to confirm what work is still required for this effort.

(See original issue for full conversation)

**Comment by ABonomo21** [comment]
Bob is working on this and it is a current github ticket... this should be closed.

**Comment by ABonomo21** [comment]
leaving open for Juanita and Bob to confirm this is being worked on.
