### ISSUE TITLE
R4C - Home Page Banner Pictures

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#35]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2238
Requested By: Ashlye Bonomo / Gary Hessong
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2238) 

**Request:** 
I am putting this ticket in because we may want to change the pictures used on the R4C start up page-

Dustin please talk to Gary about this.

**Comment by ABonomo21** [comment]
Training on this 2.11.20
