### ISSUE TITLE
R4C - Ensure Service Requests and Cases Are Not Public / Anonymous Requests

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#36]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2239 & 2326
Requested By: Ashlye Bonomo / Mike Wilkins
[2239 - Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2239) 
[2326 - Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2326) 

**Request:**
Summarizing both tickets - We need to ensure all service requests and cases are not searchable/viewable to the public. The public should be able to submit an anonymous service request on the portal. Alternative solutions have been put in place for go-live but we will need to work more with the Infor development team to get a more suitable permanent solution.

![image](https://user-images.githubusercontent.com/31770504/72629559-8fa55280-391e-11ea-9f42-f4d970f7bae3.png)

**Comment by ABonomo21** [comment]
i think what we have now is working- low priority on phase 2 in my opinion... Mike and Gary  thoughts?

**Comment by ABonomo21** [comment]
moved

**Comment by ABonomo21** [comment]
reopening as phase 2 - closed ticket from current github. Service request are working as they are not may want to still improve after July - okay per Ashlye and gary 3.4.2020

**Comment by ABonomo21** [comment]
Not required system working well.
