### ISSUE TITLE
System Wide - Inspector Name Change (KFULCHER)

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#37]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2244
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2244) 

**Request:**
Kim Fulcher's last name (and username) needs to be changed to Kim Connor.

![image](https://user-images.githubusercontent.com/31770504/72620510-6d570900-390d-11ea-8fcd-ce05ddd57d1c.png)

**Comment by ABonomo21** [comment]
this was completed.
