### ISSUE TITLE
Building Permits - RESBLDG SFD - Fire/Sprinkler Status Checks

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#39]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2293
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2293) 

**Request:**
The RESBLDG permit was generating multiple Fire/Sprinkler status checks. There are rules of when one should add versus the other but the system will currently take any Fire permit to satisfy both checks. Dan indicated we could fix this later.

![image](https://user-images.githubusercontent.com/31770504/72621671-b8721b80-390f-11ea-8a64-734a41a6ccd3.png)

**Comment by ABonomo21** [comment]
the status checks seem to be working staff will monitor and open as needed.
