### ISSUE TITLE
Building Permits - Capacity Permit - Automating Inspection Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#4]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2356
Requested By: DUSWM (B. Teach; L. Englar; T. May)
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2356) 

**Request:**
Currently, the Capacity Permit requires DUSWM staff to manually insert the appropriate inspection fee during the Under Review milestone. The manual addition of the fee was due to the variation in the inspection fee amount. Brenda Teach has since confirmed that this inspection fee will now be $60 for all permits moving forward.
![image](https://user-images.githubusercontent.com/31770504/72379039-9d6d9480-36e0-11ea-81b0-e3260383bd78.png)

As a result of this update, DUSWM would like the inspection fee to automatically add along with the other water/sewer/meter fees.

**Comment by ABonomo21** [comment]
closing for new list from duswm meeting 4.6.21
