### ISSUE TITLE
System Wide - Verify Fee Budget Codes Are Correct

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#40]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2294
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2294) 

**Request:**
Ticket initially created to correct impact fee budget codes, but then broadened to include ALL fees. Jeff Wisner worked on these and reported all fee budget codes should now be correct.

Need to confirm we have not identified any budget code issues post go-live.

**Comment by ABonomo21** [comment]
Need to keep open - This is related to a current github ticket that we should set up time for Dan to meet with Jeff W. on (which i think has already been set up for when Dan is on site?

**Comment by ABonomo21** [comment]
moved
