### ISSUE TITLE
System Wide - Update R4C Portal URL On Notifications and Reports

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#41]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2315
Requested By: Ashlye Bonomo / Project Team
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2315) 

**Request:**
Once we have the correct URL for the portal we will need to update the notifications with the link and all reports that show the URL.

**Comment by ABonomo21** [comment]
This was corrected and can be closed- Jeff Wisner should be shown by Juanita or even possibly Tara is he has not already been shown how to update notifications. 

This can be closed once something is set up or documentation is created on how IIT can make these changes in the future.

**Comment by ABonomo21** [comment]
Teach Jeff how to do this

**Comment by JuanitaMiles** [comment]
Created a quick document on how to update language on notification templates and provided to Jeff.

**Comment by JuanitaMiles** [comment]
Protal URL has been updated on notifications. Documentation has been provided to IIT on how to update basic notification templates. Will create a separate ticket outlining the need for training and documentation for reports overall.
