### ISSUE TITLE
Building Permits - Under Review in Life Permits Not Holding

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#42]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2317
Requested By: Ashlye Bonomo / Dan Grendon
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2317) 

**Request:**
See 196480 NONRESBLDG

Ashlye Commented: this application is correct - will make sure it is correct in the data migration post go live

**Comment by ABonomo21** [comment]
This has been working, we have manually moved applications as needed.
