### ISSUE TITLE
CDR Common - Bond Class Type Cleanup

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#43]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2321
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2321) 

**Request:**
Would like to clean up the available Bond Class types. This needs to be done in the Code Definition Management as a business as usual task. Types would be expired, not deleted.

Ensure Planning and Building look through these types.

![image](https://user-images.githubusercontent.com/31770504/72628662-bb273d80-391c-11ea-8298-b276d7753de8.png)

**Comment by ABonomo21** [comment]
I believe this has all been corrected. Please confirm with Emily and then close
