### ISSUE TITLE
Building Permits - Confirm Void H7 Migration and Report

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#44]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2323
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2323) 

**Request:**
Voided application should not show on the Pending Reviews on demand report. It was discovered that some applications were not voided correctly, therefore reviews were still showing on the report. We need to confirm that H7 applications that were voided have been migrated correctly and all reviews have been closed out so they do not show in the pending reviews report in the future.

**Comment by ABonomo21** [comment]
closing this issue. I think there have been issues with the data migration but whats done is done and staff is working on clean up as we go. Closing ticket.
