### ISSUE TITLE
Business License - Liquor License - Missing Endorsement Types

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#45]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2329
Requested By: Liquor Board / Tara Feaga
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2329) 

**Request:**
Endorsement types that are missing and need to be added:

- Entertainment (no fee associated)
- Patio (no fee associated)
- Growler Permit Wine Beer/Wine
- Growler Permit Wine Only

Need to confirm these have been added.

**Comment by ABonomo21** [comment]
I think this is also something Jeff Wisner can take on as a low priority.

**Comment by JuanitaMiles** [comment]
Will move and assign to Jeff as a maintenance task.

**Comment by JuanitaMiles** [comment]
Migrated over to current github for Jeff to address. Closing ticket.
