### ISSUE TITLE
Project - Blanket - Missing "Items" on the Blanket Details Page

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#46]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2338
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2338) 

**Request:**
The remaining blanket items that are missing in IPS11 needed new codes because they were over 10 characters. A spreadsheet was provided. Need to confirm these items have made it into IPS11 post go-live.

**Comment by ABonomo21** [comment]
This is something that we can assign to Jeff Wisner and should be moved to the current github.

**Comment by ABonomo21** [comment]
moved to github
