### ISSUE TITLE
Planning - SHA Review Cycle Issues (PWConstruct)

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#47]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2341
Requested By: Ashley Reed / Mike Wilkins
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2341) 

**Request:**
SHA reviews were not adding to the PWConstruct application type properly. Automatic readd on resubmit and cycle numbers were the issue. It appears PWConstruct was corrected prior to go-live but the remaining AP types may need the same fix post go-live.

**Comment by AReed327** [comment]
Closing ticket. Related to Parcel Layer and Road designation ticket in post go live ticket 123
