### ISSUE TITLE
Trade License - Renewal Review Approval Causing Duplicated Contact Relationships

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#48]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2346
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2346) 

**Request:**
A duplicate relationship for a company is created when you approve the renewal review. Noted to confirm this is no longer an issue post go-live.

License # EM250953
![image](https://user-images.githubusercontent.com/31770504/72640367-bc189900-3935-11ea-8a97-b1e538e1b132.png)

**Comment by ABonomo21** [comment]
I think this issue was resolved already. I have not seen this happen since go live. Closing ticket. Will follow up after the meeting regarding ticket #51
