### ISSUE TITLE
Trade License - Grace Exp Date On Old Licenses

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#49]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2347
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2347) 

**Request:**
We need to ensure the grace expiration dates on all licenses have migrated properly to IPS. In some cases the grace exp was populating the same as the expire date, while another issue was identified where the license went to awaiting renewal details even though it was past the grace exp date.

**Comment by ABonomo21** [comment]
combine with #51
