### ISSUE TITLE
Building Permits - Capacity Permit - Permit Fee Redesign

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#5]
**Source:**
Meetings and
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2036
Requested By: Project Team (DUSWM, D. Grendon, J. Miles...)
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2036) 

**Request:**
DUSWM has a very large fee schedule that separates water and sewer fees out by occupancy type and subdivision. Through discussions, we have discovered these fees were setup in this manner as a way for the DUSWM team to complete their financial tracking/reconciliation, but the fee values for many of these are the same. In reality there are only 5 or 6 different fee values. Such a large number of fees makes configuration of the system overly complicated and difficult. 

The Infor team has suggested a redesign of the DUSWM fees to consolidate them as much as possible. As we determine how best to consolidate we will need to ensure we still provide the DUSWM team with a way to track and report on fees by subdivision.

**Comment by ABonomo21** [comment]
i think Jeff Wisner should attempt to do this new a/p creation , fee correction, inspection etc in Test. related to ticket #4

**Comment by ABonomo21** [comment]
closing for new list from duswm meeting 4.6.21
