### ISSUE TITLE
System Wide - Contact and Property Browser Relationships Expired Date

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#50]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2348
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2348) 

**Request:**
Relationships listed in the grid for a contact in Contact and Property Browser are showing as expired on 1/1/2001. These relationships aren't actually expired.

Christian commented this is a known issue and is expected to be resolved in the 19.12 release.

![image](https://user-images.githubusercontent.com/31770504/72641810-fc2d4b00-3938-11ea-9d86-235759e18527.png)

**Comment by ABonomo21** [comment]
lets follow up on this one- this is still an issue and was not resolved in the 19.12 release...

**Comment by ABonomo21** [comment]
follow up with product team

**Comment by JuanitaMiles** [comment]
Low priority, but needs to be addressed. Dan to follow up.
