### ISSUE TITLE
Trade License - Renewal Review Resubmit Result Option

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#51]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2352
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2352) 

**Request:**
Would like to add a "resbumit" review option to the trade licence renewal review. as applicants may be missing information at renewal. Currently approved is the only option. Dan indicated that this was not the intended use for this review. Agree to re-evaluate after go-live.

![image](https://user-images.githubusercontent.com/31770504/72745699-566b1d80-3b7e-11ea-9fcb-aa9f58a39f6f.png)

![image](https://user-images.githubusercontent.com/31770504/72746109-4b64bd00-3b7f-11ea-8e8a-7e6ec2c7d472.png)

**Comment by ABonomo21** [comment]
We need to move this one to current Github - Trade Licenses need work. I would like to have some time set up for Shannon, Abbie and I to meet with Dan when he is on site to walk through issues we have had on license renewals and new licenses. Once moved to current github, this can be closed.

**Comment by ABonomo21** [comment]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2347
Requested By: Ashlye Bonomo
Jump to this repository

Request:
We need to ensure the grace expiration dates on all licenses have migrated properly to IPS. In some cases the grace exp was populating the same as the expire date, while another issue was identified where the license went to awaiting renewal details even though it was past the grace exp date.

**Comment by ABonomo21** [comment]
moved to the current github
