### ISSUE TITLE
KCI Assistance After Go-Live - Dashboards

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#52]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2353
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2353) 

**Request:**
Need to make sure all staff has dashboards set up in the new environment- Juanita can possibly help with this??

**Comment by ABonomo21** [comment]
I think we can close this but it would be helpful for there to be training material for IIT so they know how to modify and create new Dashboards for future needs of the County. Also something Jeff can work on in Test.

**Comment by JuanitaMiles** [comment]
I met with Jeff some time ago to show him how Ad Hoc Reports work and how to create them. If documentation is required, we can discuss.

**Comment by JuanitaMiles** [comment]
Initial training has been provided to Yaciel on Ad Hoc reports. Will provide additional assistance as requested. Closing ticket.
