### ISSUE TITLE
Building Permits - Capacity - Fee Needs to be Unexpired

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#54]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2358
Requested By: Lauren Englar / Juanita Miles
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2358) 

**Request:**
Lauren E. reported that RESIDENTIAL SEWER FEE 21400 is missing in IPS and needs to be made available with a value of $7509.00

Per email exchange with Dan (12/5/2019 11:49 AM), I communicated the following information:
FYI – The Fee exists in IPS it just shows as expired. I asked Lauren if it should be expired and she said it should not. I told her that if it comes over in the final migration as being expired still, we will unexpire it.

Marking as a post go live correction. 

Need to confirm if this has been addressed.

**Comment by ABonomo21** [comment]
Do we think that we can task Jeff Wisner with creating a new A/P for capacity permits in Test and have him tasked with trying to create the logic behind it including the enhancements to how fees are generated? Might be a great learn experience for Jeff and the IIT team. I would think it is probably pretty similar to how we created a new A/P and logic in Hansen 7.

**Comment by JuanitaMiles** [comment]
migrated to Post Go Live repository as a task for Jeff Wisner to confirm this fee is not expired in the system and is available for use if needed. Ticket # 395
