### ISSUE TITLE
Building Permits - Inspector Photos on Inspection Notifications

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#55]
**Source:**
Repository: dhenry-KCI / FredCo-Post-Go-Live
Ticket #: 245
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/245) 

**Request:**
Based on ticket #215 - opening a new ticket to ensure the photo of the inspector is added to our notifications.

This is not a new request this was supposed to be working prior to go-live only label option was enhancement.

**Comment by JuanitaMiles** [comment]
This is currently in progress by Christian, and almost complete.

**Comment by ABonomo21** [comment]
Because this is in the current list, I think we can close this one.
