### ISSUE TITLE
System Wide - Fee "Applied By" Usernames

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#56]
**Source:**
Repository: dhenry-KCI / FredCo-Post-Go-Live-
Ticket #: 172
Requested By: Ashley Reed / Project Team
[Jump to this repository](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/172) 

**Request:**
I'm concerned that the Fee applied by seems to be populating as the last person who accessed the file. This project # 19913 indicates that Alicia Evangelista with the health department applied planning fees to the project.
Thoughts on the significance of the applied by person? I think it could lead to issues and confusion since the HEALTH dept would never be adding our fees.

![image](https://user-images.githubusercontent.com/31770504/72818039-c9d16580-3c38-11ea-93fb-d96d09ca5e90.png)

**Comment by JuanitaMiles** [comment]
Dan implemented a solution to add a "System Generated" true/false field to the fees grid. Will follow up if county wants more on this issue.

**Comment by ABonomo21** [comment]
This is also something I would like to have but as long as there is a "system generated" true/false, I think we can probably close this one just accepting that it is probably no different than Hansen 7. Open to discuss.
