### ISSUE TITLE
System Wide - Downloading Attachments on a Smart Phone / Tablet

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#59]
**Source:**
Repository: dhenry-KCI / FredCo-Post-Go-Live-
Ticket #: 303 / 230
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/303)
[Jump to this repository](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/230)

**Request:**
Attachment are viable and editable from an IPhone and Android, however, you cannot open them.

Dan indicated that this is correct behavior per Mark Oliver. In a future release you will be able to download attachments.

**Comment by ABonomo21** [comment]
This is definitely functionality I would like to have- Mark Oliver and team I believe is looking into this for a future release.

**Comment by ABonomo21** [comment]
follow up with Mark oliver

**Comment by JuanitaMiles** [comment]
May need to confirm if this functionality is now available. Release notes for R4C 20.05 indicates downloads on phones is now supported. No comments indicate IPS Back Office 20.05 is required for this functionality to become available.

![image](https://user-images.githubusercontent.com/31770504/86821632-a40a1280-c058-11ea-9f55-9914232cb0cc.png)

**Comment by ABonomo21** [comment]
Tested downloads are now available on smart phones 7.9.20
