### ISSUE TITLE
Planning - New "DUSWM" AP Type

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#6]
**Source:**
Meetings
Requested By: Mike WIlkins, Ashley Reed

**Request:**
DUSWM staff that reviews planning applications sometimes have a need to create new back office planning application for things like City projects because DUSWM still manages their utilities. DUSWM is currently creating applications with the AP types that currently exist, however this is causing confusion and extra staff efforts due to a need to consistently waive fees, reviews, hearings, etc.

To eliminate this issue, it would be ideal to have a separate AP type where DUSWM can create the necessary application for their office only. The initial thought is that this application type can have Work Type options that would include Site,Plat, PWConstruct, etc. The workflow/milestones will be minimal.

**Comment by JuanitaMiles** [comment]
Plan to give to Jeff to attempt to create this simple AP type for planning. Will need to document the workflow for Jeff before handing off.

**Comment by ABonomo21** [comment]
closing on current github list
