### ISSUE TITLE
Trade License - Last Renewal query 

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#66]
Moving to phase 2 from ticket 522 in current

Can we add a last renewal date within a date range to the query field for Trade Licenses?
![image](https://user-images.githubusercontent.com/47611580/79786446-75ab4f80-8313-11ea-8d02-e6fae814047b.png)

Every year we have to run performance indicators that show how many applications were processed, reviews completed and inspections performed.

One of those components is how many Trade Licenses were issued and renewed within the specific FY date ranges. I do not have a way to run the renewed licenses.

Even when I perform the generic search there is no last renewal date in the column personalization options, we have next renewal .. but that doesn't help
![image](https://user-images.githubusercontent.com/47611580/79786472-7cd25d80-8313-11ea-8916-03826c2ef9d4.png)

@pooldaddy I created an ad hoc report to meet Ashlye's needs for this. BUT it'll be a "nice to have" item to add this "Last Renewal Date" to the regular Trade License lookup window. This will be a good training/learning opportunity for you and Yaciel, as these requests might come up again periodically in the future. Look into when you have time some time but not a high priority.

**Comment by JuanitaMiles** [comment]
Migrated to FredCo_Phase2_FY21 ticket # [7](https://github.com/JuanitaMiles/FredCo_Phase2_FY21/issues/7)

**Comment by ABonomo21** [comment]
done
