### ISSUE TITLE
Building Application Condition Clean Up

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#67]
![image](https://user-images.githubusercontent.com/47611580/79787067-624cb400-8314-11ea-8398-f0c2d66c1209.png)

moved from ticket 506 on current list- ab

**Comment by JuanitaMiles** [comment]
want to ensure any needed planning condition cleanup efforts are also included.

**Comment by ABonomo21** [comment]
closed
