### ISSUE TITLE
Code Enforcement - Violation (Liquor Case) - Workflow Cleanup

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#7]
**Source:**
Meeting (1/14/20)
Requested By: Juanita Miles, Dawn Shugars, Ashley Kneessi

**Request:**
Juanita spent some time on 1/14 working with the Liquor Board on how best to enter their Cases into the IPS system. Because their cases are very straight forward and move to adjudication very quickly, there may be some opportunity to bypass several of the milestones that require inspections and move to the hearing milestones earlier in the workflow. These updates will need to implemented while staying within the original framework/milestones already in place, as previously discussed with Ashlye B.

**Comment by ABonomo21** [comment]
This is something i would think that Jeff Wisner could help with down the road in a phase 2 of the project. The framework for all code enforcement cases is in place it is a matter of modifying which milestones are one and when they populate etc. i think this can be closed.

**Comment by ABonomo21** [comment]
resolved with Christian
