### ISSUE TITLE
Planning - NID and VERIFY - Add Completeness Check Milestone

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#8]
**Source:**
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2096
Requested By: Mike Wilkins, Ashley Reed
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2096) 

**Request:**
The Completeness Check/Intake Review milestone needs to be added to the workflow for the NID and VERIFY application types.

**Comment by ABonomo21** [comment]
moved to current github
