### ISSUE TITLE
PIREV - Permits and Inspections Review

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#92]
![image](https://user-images.githubusercontent.com/47611580/85039941-41f37700-b156-11ea-8bef-42194c68248c.png)

We need to make a PIREV available for all building and use a/p types 
This review will be manually added at the revision assignment milestone in the event that a revision is received and the applicant did not provide the details and information needed to submit a review back to the requesting agency. 

There should not be a revision fee assessed if this review is resulted as a resubmit and therefore should be excluded from the fee generation similar to health review resubmits.

**Comment by JuanitaMiles** [comment]
Migrated to FredCo_Phase2_FY21 ticket # [3](https://github.com/JuanitaMiles/FredCo_Phase2_FY21/issues/3)

**Comment by ABonomo21** [comment]
done
