### ISSUE TITLE
Historic Parcel Detail and Permit/Planning Code Change

### ISSUE THREAD

**Issue by ABonomo21** [JuanitaMiles/FredCo_Future_Phases#98]
Per conversation with Juanita and Dan on 6.22.20- 

I was able to speak with Mary M. after the call with Amanda W. and Kim B. and the push into the IPS data did trigger those additional 5000 parcels to be marked as a “Y” on the parcel details. 

Because of that it has resulted in additional historic reviews on building permits.

We are going to have the Historic Parcel Detail field changed from a Y or N data field or a check box that indicates Y to a data field for values such as C-County registry, S-State registry and N-National Registry (along with any others required will get list from Mary and Amanda). 

Then we will just have to recode our permits to change that if the parcel is marked with a Y which previously only designated those parcels on the County Registry to a C and the historic review will generate. Then for demo and grading permits with marked with an S or C it will trigger the historic review. 

I have included Ashley Reed to make sure we are able to capture any of the planning changes that would be needed however, it should not change much for planning because Amanda as you stated it should trigger the review regardless of the designation, correct? Therefore, we should just change the planning code to say if historic field is null do not add the review, if data entered add the historic review.

**Comment by AReed327** [comment]
I'd like to have a conversation about this. I distribute Historic reviews for other reasons than just a historic designation on the property. I need to be confident that if I put a check in the Historic box on the details tab on a planning application, that the Historic review is going to populate same as it currently does.  AREED

**Comment by JuanitaMiles** [comment]
Migrated to FredCo_Phase2_FY21 ticket # [4](https://github.com/JuanitaMiles/FredCo_Phase2_FY21/issues/4)

**Comment by ABonomo21** [comment]
done
